### ISSUE TITLE
Hyprcursors

### ISSUE THREAD

**Issue by nonetrix** [guillaumeboehm/Nordzy-cursors#8]
Could this theme be converted to Hyprcursors format? This would be nice, should mean that it uses vector scaling so it can be scaled infinitely

**Comment by andrrrw** [comment]
if it is still relevant
https://github.com/guillaumeboehm/Nordzy-cursors-hyprcursor

**Comment by andrrrw** [comment]
Nope
there another fork from another dude
i don't develop this

**Comment by nonetrix** [comment]
Well ask them I guess

**Comment by nonetrix** [comment]
@guillaumeboehm are you interested or nah?

**Comment by guillaumeboehm** [comment]
Yeah, I guess so. I made a quick theme using the extract tool just to use it for myself but I guess I can take some time to make proper hypercursors using the SVGs. Whether it would be merged in here or not afterward I don't know though.

**Comment by guillaumeboehm** [comment]
@nonetrix https://github.com/guillaumeboehm/Nordzy-cursors-hyprcursor/releases/tag/2.0.0

**Comment by guillaumeboehm** [comment]
Hyprcursors are now generated in this repo.
